### ISSUE TITLE
Issues on mobile Safari and mobile Chrome

### ISSUE THREAD

**Issue by tiefenb** [jaicab/localFont#10]
I have some issues in mobile Safari and mobile chrome... the font-css are loaded into the localStorage but it wont be render...

any ideas why?

**Comment by jaicab** [comment]
Can you please give more information about it? Like:
- File type
- Total weight of the CSS
- Demo if possible

Have you changed anything in script? Do you have your font.css file in the root?

**Comment by tiefenb** [comment]
Hi, thanks.

I just saw, it also don't work on desktop safari.
here is the url: http://derbrutkasten-v2.herokuapp.com

**Comment by tiefenb** [comment]
...and yes. I added an cache-buster feature as parameter to the font.css

**Comment by jaicab** [comment]
Ok it seems to work fine [on Chrome in OSX](https://cloud.githubusercontent.com/assets/1174434/10689170/1f1d056a-7971-11e5-9e44-8123283db329.png).
On Safari I am getting a JS error, maybe that's preventing localFont's from being executed?

![screen shot 2015-10-23 at 10 34 36](https://cloud.githubusercontent.com/assets/1174434/10689278/b3c1089c-7971-11e5-898b-84e7cabfad1d.png)

**Comment by jaicab** [comment]
Since this is working on every other browser and this JS error is only appearing on Safari I'll assume that is the problem. If it's not I'll reopen the issue.

**Comment by tiefenb** [comment]
I fixed the JS bug, but the font still won't load

**Comment by jaicab** [comment]
I just realised you're just using *.woff2. That means you [don't get support in Safari](http://caniuse.com/#feat=woff2). I would recommend using *.woff for broader support.

**Comment by tiefenb** [comment]
Ah, okay! thanks

2015-10-23 12:44 GMT+02:00 Jaime Caballero notifications@github.com:

**Comment by jaicab** [comment]
No worries mate! Thanks for using localFont! :)
