### ISSUE TITLE
woff2 outputs base64 with "data:font/truetype" instead of "data:font/woff2"

### ISSUE THREAD

**Issue by janpe** [jaicab/localFont#4]
Tried to encode woff2 fonts but got font with "data:font/truetype" instead of "data:font/woff2".

**Comment by jaicab** [comment]
The support for specific MIME types for woff2 was unclear, but seems like font/woff2 is not the recommended option to go right now, but application/font-woff2. You can still edit the MIME types to adapt them to your needs though.
[Check this out](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a) to know more about it.

Updating this right now, thanks for the heads up. :+1:

**Comment by jaicab** [comment]
Fixed!
