### ISSUE TITLE
Add multiple font family support

### ISSUE THREAD

**Issue by jaicab** [jaicab/localFont#5]
Currently, there is no way to manage more than one font family at a time. 
It would be nice to have that ability, but it would mean to have draggable rows as right now they are automatically sorted using the data.

**Comment by dubrod** [comment]
This might be kinda hackish but you can call multiple font families, just change `font_css_cache` to `font_css_cache67` or something. I've done it, 67 being a different weight font. I think you have to change it in like 5 spots.
